favicon: /favicon.ico
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  icon: flag-cn
  name: Chinese



menu:
  - name: æˆ‘çš„ç½‘ç«™
    icon: far fa-star
    config: hotTools
  - name: å·¥å…·åº”ç”¨
    icon: fas fa-paper-plane
    config: imTools
  - name: ç´ æèµ„æº
    icon: fas fa-blog
    config: news
  - name: çµæ„Ÿè®¾è®¡
    icon: fas fa-tools
    config: devTools
  - name: å­¦ä¹ èµ„æ–™
    icon: fas fa-book
    config: Student
  - name: æ¸¸æˆå¨±ä¹
    icon: fas fa-gamepad
    config: Games
      

devTools:
  - name: ChatGPT
    url: https://chat.sakurachu.cn/
    img: /images/logos/chat.png
    description: å›½å†…å¯ç”¨ğŸ”¥
  - name: NewBing
    url: https://bing.sakurachu.xyz/
    img: /images/logos/bing.png
    description: å›½å†…å¯ç”¨ğŸ”¥
  - name: LogoBook
    url: http://www.logobook.com/
    img: /images/logos/logobook.ico
    description: è®¾è®¡Logo
  - name: Gradientify
    url: https://www.iconshock.com/svg-icons/
    img: https://www.iconshock.com/svg-icons/favicon.ico
    description: æ¸å˜çŸ¢é‡å›¾æ ‡è®¾è®¡
  - name: illlustrations
    url: https://illlustrations.co/
    img: /images/logos/illlustrations.jpg
    description: æ™®é€šçŸ¢é‡å›¾æ ‡è®¾è®¡
  - name: æ˜“è¯äº‘
    url: https://www.yciyun.com/
    img: https://www.yciyun.com/favicon.ico
    description: å…¨èƒ½è¯äº‘ç”Ÿæˆå·¥å…·


hotTools:
  - name: Sakura
    url: https://www.sakurachu.cn/
    img: /images/logos/blog-logo.png
    description: WelcomeğŸŒ¸
  - name: ChatGPT
    url: https://chat.sakurachu.cn/
    img: /images/logos/chat.png
    description: å›½å†…å¯ç”¨ğŸ”¥
  - name: NewBing
    url: https://bing.sakurachu.xyz/
    img: /images/logos/bing.png
    description: å›½å†…å¯ç”¨ğŸ”¥
  - name: Humsun
    url: ç§å¯†é“¾æ¥éœ€è¦è®¿é—®å¯†ç ï¼Œè¯·å‹¿éšæ„ç‚¹å‡»ã€‚
    img: /images/logos/Logo2.ico
    description: ç§ç”¨ç½‘ç«™ï¼Œè¯·å‹¿éšæ„ç‚¹å‡»âš ï¸
  - name: ä¸ªäººåšå®¢
    url: https://blog.sakurachu.cn/
    img: /images/logos/github.png
    description: å»ºè®¾ä¸­ğŸš§...

news:
  - name: Videvo
    url: https://www.videvo.net/
    img: https://www.videvo.net/favicon.ico
    description: å…è´¹è§†é¢‘ç´ æ
  - name: Mixkit
    url: https://mixkit.co/
    img: https://mixkit.co/favicon.ico
    description: é«˜è´¨é‡å…è´¹è§†é¢‘
  - name: Smartmockups
    url: https://smartmockups.com/zh/
    img: https://smartmockups.com/zh/favicon.ico
    description: ç”Ÿæˆæ ·æœºäº§å“å®æ™¯å›¾
  - name: All iconsets
    url: https://icon-icons.com/
    img: https://cdn.icon-icons.com/images/apple-touch-icon-iphone-60x60-precomposed.png
    description: icoç´ æç½‘ç«™
  - name: å½¼å²¸å›¾ç½‘
    url: https://pic.netbian.com/
    img: /images/logos/bianwang.ico
    description: 4Kå£çº¸ä¸‹è½½
  - name: IOSPA
    url: https://www.iosipa.cn/
    img: https://www.iosipa.cn/favicon.ico
    description: å…è´¹IOSè½¯ä»¶
  - name: Dreamstime
    url: https://cn.dreamstime.com/free-photos/
    img: https://cn.dreamstime.com/favicon.ico
    description: å…è´¹ç…§ç‰‡ç±»å›¾åº“
  - name: Music maker
    url: https://musicmaker.site/
    img: /images/logos/Musicmaker.jpg
    description: å…è´¹èƒŒæ™¯éŸ³ä¹
  - name: Gitmoji
    url: https://gitmoji.dev/
    img: https://gitmoji.dev/static/apple-icon-57x57.png
    description: emojiå°å›¾æ ‡
  - name: Gameicons
    url: https://game-icons.net/
    img: https://game-icons.net/favicon.ico
    description: æ¸¸æˆå›¾ç‰‡ç´ æ
  - name: LaTeX
    url: http://www.latextemplates.com/
    img: http://www.latextemplates.com/apple-touch-icon.png
    description: å„ç±»ä¸“ä¸šæ¨¡æ¿
  - name: ç™¾åº¦æŒ‡æ•°
    url: https://index.baidu.com/v2/
    img: https://www.baidu.com/favicon.ico
    description: äººä»¬çš„å…³æ³¨ç‚¹


Student:
  - name: å®‰å¨œçš„æ¡£æ¡ˆ
    url: https://zh.annas-archive.org/
    img: https://zh.annas-archive.org/favicon.ico
    description: ä¹¦ç±ä¸‹è½½ğŸš€
  - name: Project Gutenberg
    url: https://www.gutenberg.org/
    img: https://www.gutenberg.org/favicon.ico
    description: ä¹¦ç±æ–‡æ¡£ä¸‹è½½
  - name: Doyoudo
    url: https://www.doyoudo.com/
    img: https://www.doyoudo.com/favicon.ico
    description: è®¾è®¡æ•™ç¨‹
  - name: CPAM
    url: https://onlinelibrary.wiley.com/journal/10970312
    img: https://onlinelibrary.wiley.com/favicon.ico
    description: æ•°å­¦æœŸåˆŠ
  - name: Annals
    url: https://annals.math.princeton.edu/
    img: /images/logos/Annals.png
    description: æ•°å­¦æœŸåˆŠ
  - name: KuKu
    url: https://dazi.kukuw.com/
    img: https://dazi.kukuw.com/favicon.ico
    description: æ‰“å­—æµ‹è¯•


Games:
  - name: æ¸¸æˆæŠ˜æ‰£
    url: https://indienova.com/steam/discount/4-0-0-0-0-0-0-0-0/p/1
    img: https://indienova.com/favicon.ico
    description: Steam PSN Switch
  - name: ç½‘é£èµ„æº
    url: https://www.naifei.im/
    img: https://www.naifei.im/mxtheme/images/favicon.png
    description: æœ€æ–°æœ€å…¨å½±è§†èµ„æº

about:
  url: /about/
  icon: far fa-heart
  name: å…³äºæœ¬ç«™

aboutPage:
  website:
    head: æ¬¢è¿è®¿é—®æˆ‘çš„å¯¼èˆªé¡µğŸŒ¸~
    html: '<blockquote><p>æˆ‘çš„ç½‘ç«™æ˜¯ä¸€ä¸ªé›†æˆäº†å¾ˆå¤šå·¥å…·çš„å¯¼èˆªé¡µã€‚å®ƒæä¾›äº†æœ€æ–°çš„å„ç§å·¥å…·å’Œèµ„æ–™ï¼ŒåŒ…æ‹¬æœ€æ–°çš„AIå·¥å…·ï¼Œæ–¹ä¾¿ç”¨æˆ·æ ¹æ®éœ€è¦ç›´æ¥è·³è½¬åˆ°å¯¹åº”çš„é“¾æ¥ã€‚</p>
    <p>æ— è®ºä½ æ˜¯éœ€è¦æŸ¥æ‰¾æœ€æ–°çš„è½¯ä»¶å·¥å…·ã€å­¦ä¹ ç¼–ç¨‹çŸ¥è¯†ã€è·å–è®¾è®¡çµæ„Ÿï¼Œè¿˜æ˜¯å¯»æ‰¾å…è´¹çš„å­¦ä¹ èµ„æºï¼Œæˆ‘çš„ç½‘ç«™éƒ½èƒ½æ»¡è¶³ä½ çš„éœ€æ±‚ã€‚</p>
    <p>æˆ‘ä»¬ä¸æ–­æ›´æ–°å’Œæ·»åŠ æ–°çš„å·¥å…·å’Œèµ„æºï¼Œç¡®ä¿ä½ å§‹ç»ˆèƒ½å¤Ÿæ‰¾åˆ°æœ€æ–°ã€æœ€æœ‰ç”¨çš„å†…å®¹ã€‚é€šè¿‡æˆ‘çš„ç½‘ç«™ï¼Œä½ å¯ä»¥çœå»åœ¨ä¸åŒç½‘ç«™ä¹‹é—´åˆ‡æ¢çš„éº»çƒ¦ï¼Œä¸€ç«™å¼è·å–ä½ æ‰€éœ€çš„ä¸€åˆ‡ã€‚</p>
    <p>æ— è®ºä½ æ˜¯å­¦ç”Ÿã€å·¥ç¨‹å¸ˆã€è®¾è®¡å¸ˆè¿˜æ˜¯ä»»ä½•å¯¹æŠ€æœ¯å’Œåˆ›æ„æ„Ÿå…´è¶£çš„äººï¼Œæˆ‘çš„ç½‘ç«™éƒ½èƒ½ä¸ºä½ æä¾›å¸®åŠ©å’Œæ”¯æŒã€‚</p>
    <p>è¯·éšæ—¶æµè§ˆæˆ‘çš„ç½‘ç«™ï¼Œå¹¶å°†å®ƒæ·»åŠ åˆ°ä½ çš„ä¹¦ç­¾ä¸­ï¼Œæ–¹ä¾¿ä½ éšæ—¶è®¿é—®ã€‚å¦‚æœä½ æœ‰ä»»ä½•å»ºè®®æˆ–éœ€è¦å¸®åŠ©ï¼Œè¯·è”ç³»æˆ‘ä»¬ï¼Œæˆ‘ä»¬å°†å°½åŠ›æ»¡è¶³ä½ çš„éœ€æ±‚ã€‚</p>
    <p>æ²¡é”™ï¼Œè¿™ä¸ªç½‘é¡µä»‹ç»å°±æ˜¯AIç”Ÿæˆçš„~</p>
    <p>PSï¼šæ³¨æ„å¯¼èˆªé¡µä¸­å¸¦æœ‰ğŸš€éœ€è¦é­”æ³•è®¿é—®ï¼ŒBingAIä½¿ç”¨éœ€è¦å»å³ä¸Šè§’è®¾ç½®å¯¼å…¥è‡ªå·±çš„Cookieæ–¹å¯ä½¿ç”¨ã€‚</p>
    </blockquote>'
  webmaster:
    head: å…³äºä¸»ç«™
    name: Sakuraå¯¼èˆªé¡µ
    url: https://www.sakurachu.cn
    img: /images/logos/blog-logo.png
    description: äº¤æµåˆ†äº«äº’è”ç½‘ç§‘æŠ€
    html: '<br /><blockquote><p>åŒæ—¶æ¬¢è¿è®¿é—®ä¸ªäººåšå®¢<a href="https://blog.sakurachu.cn" target="_blank" rel="noopener"> Sakura</a> è·å–æ›´å¤šå†…å®¹ã€‚</p></blockquote>'

since: 2020

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: æœ¬ç«™æ€»è®¿é—®é‡$pv
  uv: æœ¬ç«™æ€»è®¿å®¢æ•°$uv

custom:
  head: |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°<head></head>æ ‡ç­¾å†…ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼ æ³¨é‡Šè¯¥è¡Œç›´æ¥æ¢æˆHTMLå³å¯
    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->
    <!-- å¯è®¾ç½®å¤šè¡Œ -->

  body: ''
#  |- # ä»¥ä¸‹å†…å®¹æ’å…¥åˆ°</body>æ ‡ç­¾ä¹‹å‰ï¼Œå¯è®¾ç½®å¤šè¡Œï¼Œæ³¨æ„æ¯è¡Œå¼€å¤´è‡³å°‘å››ä¸ªç©ºæ ¼
#    <!-- ç›´æ¥æ·»åŠ htmlå†…å®¹å³å¯ -->
#    <!-- å¯è®¾ç½®å¤šè¡Œ -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
